name: chatter
description: "A new Flutter project."
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: ^3.11.5

dependencies:
  flutter:
    sdk: flutter

  google_fonts: ^8.1.0
  firebase_core: ^4.9.0
  firebase_auth: ^6.5.1
  firebase_ui_auth: ^3.0.1
  cloud_firestore: ^6.4.1
  provider: ^6.1.5+1
  chat_bubbles: ^1.10.0
  image_picker: ^1.2.2
  firebase_storage: ^13.4.2

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^6.0.0

flutter:

  uses-material-design: true